### initializing 2d Array

In [1]:
import numpy as np

array=np.array([[1,2,3],[5,6,7]])

In [2]:
array

array([[1, 2, 3],
       [5, 6, 7]])

### Insertion in an Array

In [3]:
arr=np.array([[1,2,3],[5,6,7]])

In [7]:
new_arr=np.insert(arr,1,[[0,0,0]],axis=0)
#array object,Position of that, elements to be inserted,axis

In [8]:
print(arr)
print(new_arr)

[[1 2 3]
 [5 6 7]]
[[1 2 3]
 [0 0 0]
 [5 6 7]]


In [9]:
#adding to end of 2d aray
new_arr=np.append(arr,[[0,0,0]],axis=0)
print(arr)
print(new_arr)

[[1 2 3]
 [5 6 7]]
[[1 2 3]
 [5 6 7]
 [0 0 0]]


### Accesing 2d array

In [10]:
import numpy as np

array=np.array([[1,2,3],[5,6,7]])

In [11]:
len(array) #return no rows

2

In [12]:
len(array[0]) #return no columns

3

### Array traversal

In [13]:
import numpy as np

array=np.array([[1,2,3],[5,6,7]])

In [14]:
for i in range(len(array)):
    for j in range(len(array[0])):
        print(array[i][j],end= " ")
    print("")
    

1 2 3 
5 6 7 


### deleting element in 2d Array

In [15]:
import numpy as np

array=np.array([[1,2,3],[5,6,7]])

In [16]:
del_arr=np.delete(array,0,axis=0)

In [17]:
print(array)
print(del_arr)

[[1 2 3]
 [5 6 7]]
[[5 6 7]]


In [18]:
#Tc and sc -> O(m*n) caz allocating new space